name: Test-Lint

on: [pull_request]

jobs:
  pylint:
    name: Test Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - uses: Silleellie/pylint-github-action@v2
      with:
        lint-path: src
        python-version: 3.11