name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        pip install mypy
    - name: mypy
      run: |
        mypy .