name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install .
    - name: Run pylint test
      uses: Silleellie/pylint-github-action@v2
      with:
        lint-path: src
        python-version: 3.11
        readme-path: README.md
        badge-text: PyLint
        color-bad-score: red
        color-ok-score: orange
        color-good-score: yellow
        color-perfect-score: brightgreen
